# ComfyUI Docker Compose Configuration
# Multiple service profiles for different use cases
#
# Quick Start Commands:
# docker compose --profile core up -d       # Core ComfyUI with GPU (recommended)
# docker compose --profile complete up -d   # Complete ComfyUI with all optimizations  
# docker compose --profile cpu up -d        # CPU mode
#
# For convenience, core is also the default:
# docker compose up -d                      # Same as --profile core

# Environment Variables:
# COMFY_PORT - Port to expose ComfyUI (default: 8188)
# COMFY_IMAGE - Override default image
# COMFY_DATA_PATH - Host path containing data subdirectories (default: ./data)
# PUID - User ID for container ownership (default: 1000)
# PGID - Group ID for container ownership (default: 1000)
#
# Volume Structure:
# Each subdirectory is mounted directly to /app/[subdirectory]:
# ./data/models -> /app/models
# ./data/custom_nodes -> /app/custom_nodes
# ./data/input -> /app/input
# ./data/output -> /app/output
# ./data/temp -> /app/temp
# ./data/user -> /app/user

services:
  # Core GPU mode (--profile core, also default)F
  core-cuda:
    image: ${COMFY_IMAGE:-ghcr.io/pixeloven/comfyui-docker/core:cuda-latest}
    user: ${PUID:-1000}:${PGID:-1000}
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - COMFY_PORT=${COMFY_PORT:-8188}
      - CLI_ARGS=
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    ports:
      - "${COMFY_PORT:-8188}:${COMFY_PORT:-8188}"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      # Direct mount to ComfyUI default structure
      - ${COMFY_CUSTOM_NODE_PATH:-./data/custom_nodes}:/app/custom_nodes:rw
      - ${COMFY_INPUT_PATH:-./data/input}:/app/input:rw
      - ${COMFY_MODEL_PATH:-./data/models}:/app/models:ro
      - ${COMFY_OUTPUT_PATH:-./data/output}:/app/output:rw
      - ${COMFY_TEMP_PATH:-./data/temp}:/app/temp:rw
      - ${COMFY_USER_PATH:-./data/user}:/app/user:rw
      # Scripts for complete image features
      - ./services/comfy/complete/scripts:/app/scripts:ro
    stop_signal: SIGKILL
    tty: true
    networks:
      - comfy_network
    profiles: [core]

  # Complete GPU mode with all optimizations (--profile complete)
  complete-cuda:
    image: ${COMFY_IMAGE:-ghcr.io/pixeloven/comfyui-docker/complete:cuda-latest}
    user: ${PUID:-1000}:${PGID:-1000}
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - COMFY_PORT=${COMFY_PORT:-8188}
      - CLI_ARGS=
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    ports:
      - "${COMFY_PORT:-8188}:${COMFY_PORT:-8188}"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      # Direct mount to ComfyUI default structure
      - ${COMFY_CUSTOM_NODE_PATH:-./data/custom_nodes}:/app/custom_nodes:rw
      - ${COMFY_INPUT_PATH:-./data/input}:/app/input:rw
      - ${COMFY_MODEL_PATH:-./data/models}:/app/models:ro
      - ${COMFY_OUTPUT_PATH:-./data/output}:/app/output:rw
      - ${COMFY_TEMP_PATH:-./data/temp}:/app/temp:rw
      - ${COMFY_USER_PATH:-./data/user}:/app/user:rw
      # Scripts for complete image features
      - ./services/comfy/complete/scripts:/app/scripts:ro
    stop_signal: SIGKILL
    tty: true
    networks:
      - comfy_network
    profiles: [complete]

  # CPU-only mode (--profile cpu)
  core-cpu:
    image: ${COMFY_IMAGE:-ghcr.io/pixeloven/comfyui-docker/core:cpu-latest}
    user: ${PUID:-1000}:${PGID:-1000}
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - COMFY_PORT=${COMFY_PORT:-8188}
      - CLI_ARGS=--cpu
    ports:
      - "${COMFY_PORT:-8188}:${COMFY_PORT:-8188}"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      # Direct mount to ComfyUI default structure
      - ${COMFY_CUSTOM_NODE_PATH:-./data/custom_nodes}:/app/custom_nodes:rw
      - ${COMFY_INPUT_PATH:-./data/input}:/app/input:rw
      - ${COMFY_MODEL_PATH:-./data/models}:/app/models:ro
      - ${COMFY_OUTPUT_PATH:-./data/output}:/app/output:rw
      - ${COMFY_TEMP_PATH:-./data/temp}:/app/temp:rw
      - ${COMFY_USER_PATH:-./data/user}:/app/user:rw
      # Scripts for testing (core image compatibility)
      - ./services/comfy/complete/scripts:/app/scripts:ro
    stop_signal: SIGKILL
    tty: true
    networks:
      - comfy_network
    profiles: [cpu]

networks:
  comfy_network:
    driver: bridge 