# ComfyUI Docker Compose Configuration
# Multiple service profiles for different use cases
#
# Quick Start Commands:
# docker compose --profile core up -d       # Core ComfyUI with GPU (recommended)
# docker compose --profile complete up -d   # Complete ComfyUI with all optimizations
# docker compose --profile cpu up -d        # CPU mode
#
# For convenience, core is also the default:
# docker compose up -d                      # Same as --profile core
#
# Multi-Instance Mode:
# docker compose -f docker-compose.multi.yml up -d

# Environment Variables:
# COMFY_PORT - Port to expose ComfyUI (default: 8188)
# COMFY_IMAGE - Override default image
# COMFY_SHARED_PATH - Host path for shared resources (default: ./storage/shared)
# COMFY_INSTANCES_PATH - Host path for instance-specific data (default: ./storage/instances)
# PUID - User ID for container ownership (default: 1000)
# PGID - Group ID for container ownership (default: 1000)

services:
  # Core GPU mode (--profile core, also default)F
  core-cuda:
    image: ${COMFY_IMAGE:-ghcr.io/pixeloven/comfyui-docker/core:cuda-latest}
    user: ${PUID:-1000}:${PGID:-1000}
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - COMFY_PORT=${COMFY_PORT:-8188}
      - CLI_ARGS=
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    ports:
      - "${COMFY_PORT:-8188}:${COMFY_PORT:-8188}"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      # Shared resources (read-only)
      - ${COMFY_SHARED_PATH:-./storage/shared}:/shared:ro
      # Instance-specific data (read-write) - defaults to 'comfy' instance
      - ${COMFY_INSTANCES_PATH:-./storage/instances}/comfy:/instance:rw
      # Scripts path
      - ./services/comfy/complete/scripts:/home/comfy/app/scripts:ro
    stop_signal: SIGKILL
    tty: true
    networks:
      - comfy_network
    profiles: [core]

  # Complete GPU mode with all optimizations (--profile complete)
  complete-cuda:
    image: ${COMFY_IMAGE:-ghcr.io/pixeloven/comfyui-docker/complete:cuda-latest}
    user: ${PUID:-1000}:${PGID:-1000}
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - COMFY_PORT=${COMFY_PORT:-8188}
      - CLI_ARGS=
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    ports:
      - "${COMFY_PORT:-8188}:${COMFY_PORT:-8188}"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      # Shared resources (read-only)
      - ${COMFY_SHARED_PATH:-./storage/shared}:/shared:ro
      # Instance-specific data (read-write) - defaults to 'comfy' instance
      - ${COMFY_INSTANCES_PATH:-./storage/instances}/comfy:/instance:rw
      # Scripts path
      - ./services/comfy/complete/scripts:/home/comfy/app/scripts:ro
    stop_signal: SIGKILL
    tty: true
    networks:
      - comfy_network
    profiles: [complete]

  # CPU-only mode (--profile cpu)
  core-cpu:
    image: ${COMFY_IMAGE:-ghcr.io/pixeloven/comfyui-docker/core:cpu-latest}
    user: ${PUID:-1000}:${PGID:-1000}
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - COMFY_PORT=${COMFY_PORT:-8188}
      - CLI_ARGS=--cpu
    ports:
      - "${COMFY_PORT:-8188}:${COMFY_PORT:-8188}"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      # Shared resources (read-only)
      - ${COMFY_SHARED_PATH:-./storage/shared}:/shared:ro
      # Instance-specific data (read-write) - defaults to 'comfy' instance
      - ${COMFY_INSTANCES_PATH:-./storage/instances}/comfy:/instance:rw
      # Scripts path
      - ./services/comfy/complete/scripts:/home/comfy/app/scripts:ro
    stop_signal: SIGKILL
    tty: true
    networks:
      - comfy_network
    profiles: [cpu]


networks:
  comfy_network:
    driver: bridge 