FROM base AS extensions

# Pre-install extensions
RUN --mount=type=cache,target=~/.cache/uv,sharing=locked \
  source ~/.venv/bin/activate && \
  uv pip install -r plugin-requirements.txt

# Install extensions
RUN comfy node install ComfyUI-Manager

# @todo setup with basic extensions