FROM ghcr.io/pixeloven/comfyui-docker/comfy-nvidia:latest

USER comfy
WORKDIR /home/comfy/app

SHELL ["/bin/bash", "--login", "-c"]

COPY --chown=comfy:comfy addon-requirements.txt ./

RUN --mount=type=cache,target=~/.cache/pip \
  source ~/.venv/bin/activate && \
  pip install -r addon-requirements.txt && \
  pip cache purge

ENTRYPOINT ["./entrypoint.sh"]
CMD ["bash", "./startup.sh"] 