FROM base AS extensions

# Pre-install extensions
RUN --mount=type=cache,target=~/.cache/pip \
  source ~/.venv/bin/activate && \
  pip install -r plugin-requirements.txt

# Install extensions
RUN comfy node install ComfyUI-Manager

# @todo setup with basic extensions