FROM base as addons

USER comfy
WORKDIR /home/comfy/app

SHELL ["/bin/bash", "--login", "-c"]

COPY --chown=comfy:comfy addon-requirements.txt ./

# Copy the scripts this image needs
RUN --mount=type=cache,target=~/.cache/pip \
  source ~/.venv/bin/activate && \
  pip install -r addon-requirements.txt && \
  pip cache purge