blank_issues_enabled: false
contact_links:
  - name: Questions? Need help getting started?
    url: https://github.com/pixeloven/ComfyUI-Docker/discussions
    about: Please use GitHub Discussions for questions, setup help, and general discussion
  - name: ComfyUI Support (not Docker-related)
    url: https://github.com/comfyanonymous/ComfyUI/issues
    about: For issues with ComfyUI itself (not the Docker setup), please report upstream
