"""What a model IS, measured, versus what its filename claims.

Three sources, in DECREASING authority:

  1. `ss_sd_model_hash` / `ss_sd_model_name` in the safetensors header — the
     checkpoint the TRAINER actually used. Nobody else can restate this.
  2. Civitai BY CONTENT HASH (`/model-versions/by-hash/<sha256>`), which
     identifies a file regardless of which mirror supplied it.
  3. Civitai by the declared source id.

TWO TRAPS, both of which produced wrong answers in a real store before they
were pinned down, and both of which this module exists to avoid:

  * NEVER use `ss_base_model_version` for lineage. It reports `sdxl_base_v1-0`
    for essentially every SDXL file. That is the ARCHITECTURE, not the
    finetune, and taking it for lineage mislabels an entire store at once.
  * NEVER infer lineage from the install path. The path records where a file
    was FILED — wrong for 2 of 48 loras and 1 of 16 checkpoints. `describe()`
    is deliberately not given one, so the mistake cannot be made here.

A CORRECTION WORTH KEEPING. Earlier documentation of this tool claimed Civitai
needs a bearer token AND a non-default User-Agent. It does not need the token
for public by-hash lookups: the 403 is a block on the literal
`Python-urllib/3.12`, and every other UA tried — including a lowercased one —
returns 200 without credentials. That block silently failed 38 of 106 lookups
and was misdiagnosed as auth, which is worse than leaving it unexplained. The
token stays OPTIONAL here; whether it unlocks gated versions is untested and
should not be asserted either way.

A failed lookup means UNIDENTIFIED, never fatal. An audit tool that dies on one
bad response audits nothing.
"""

from __future__ import annotations

import json
import re
import struct
import time
from pathlib import Path
from typing import Any

import httpx
import yaml

from . import http

API = "https://civitai.com/api/v1/model-versions"
RESERVED = ("profiles.yaml", "capabilities.yaml", "_meta.yaml")
_PAUSE = 0.35  # courtesy between Civitai calls; not a correctness property


class _Dumper(yaml.SafeDumper):
    """yamllint wants sequences indented under their key; PyYAML does not."""

    def increase_indent(self, flow: bool = False, indentless: bool = False) -> None:
        return super().increase_indent(flow, False)


# The attribution line is a PARAMETER because the artifact is diffed against
# its committed form, and a generator rename would otherwise read as a content
# change. Defaults to this tool; a downstream wrapper passes its own.
DEFAULT_GENERATOR = "comfyfetch facts"

HEADER = (
    "# GENERATED by {generator} -- DO NOT HAND-EDIT.\n"
    "#\n"
    "# Measured, not declared. `trained_on` comes from ss_sd_model_hash inside the\n"
    "# safetensors file, resolved through Civitai; `declared_base` is what the\n"
    "# publisher claims for the file's CONTENT HASH. Where they disagree, the\n"
    "# disagreement is the point -- never infer lineage from a filename or folder.\n"
)


def safetensors_header(path: Path) -> dict[str, Any]:
    """The `__metadata__` block, without reading the weights.

    The length prefix is trusted only up to a sane bound: a corrupt or
    non-safetensors file would otherwise ask us to read its whole size into
    memory.
    """
    try:
        with open(path, "rb") as fh:
            n = struct.unpack("<Q", fh.read(8))[0]
            if n > 100_000_000:
                return {}
            return (json.loads(fh.read(n)) or {}).get("__metadata__", {}) or {}
    except (OSError, ValueError, struct.error):
        return {}


def _get(url: str, token: str | None) -> dict[str, Any] | None:
    """None means unidentified. Never raises."""
    try:
        with http.request(url, token=token, timeout=25) as response:
            return json.loads(response.read())
    except (httpx.HTTPError, ValueError):
        return None


def _resolve_trained_on(header: dict, token: str | None, cache: dict[str, str]) -> str | None:
    """What the trainer recorded, with a bare Civitai version id resolved.

    Trainers write either a filename or a naked id like `1234.safetensors`. The
    id is accurate and unreadable; resolving it is the difference between a fact
    and a number.
    """
    name = header.get("ss_sd_model_name")
    if not name:
        return None
    match = re.match(r"^(\d+)\.safetensors$", name)
    if not match:
        return name
    version = match.group(1)
    if version not in cache:
        body = _get(f"{API}/{version}", token)
        if body:
            model = (body.get("model") or {}).get("name") or ""
            cache[version] = f"{model} {body.get('name') or ''}".strip()
        else:
            # Recorded, not dropped: "we asked and could not tell" is a
            # different statement from "there was nothing to ask about".
            cache[version] = f"(unresolved {version})"
        time.sleep(_PAUSE)
    return cache[version]


def describe(
    name: str,
    *,
    header: dict[str, Any],
    sha: str | None,
    token: str | None,
    cache: dict[str, str] | None = None,
) -> dict[str, Any]:
    """One file's facts. NO install path parameter, deliberately — see above."""
    cache = {} if cache is None else cache
    record: dict[str, Any] = {}

    trained = _resolve_trained_on(header, token, cache)
    if trained:
        record["trained_on"] = trained

    if sha:
        body = _get(f"{API}/by-hash/{sha}", token)
        if body:
            if body.get("baseModel"):
                record["declared_base"] = body["baseModel"]
            if (body.get("model") or {}).get("nsfw"):
                record["nsfw"] = True
            if body.get("trainedWords"):
                record["trained_words_raw"] = body["trainedWords"]
        time.sleep(_PAUSE)
    return record


def render(
    lineage: dict,
    *,
    headers: dict[str, dict],
    shas: dict[str, str],
    token: str | None,
    generated: str,
    generator: str = DEFAULT_GENERATOR,
) -> str:
    """A lineage's sidecar, as text.

    `generated` is a PARAMETER rather than today's date so the output is
    reproducible: a timestamp is the difference between an artifact that can be
    diffed against its committed form and one that cannot.
    """
    cache: dict[str, str] = {}
    facts: dict[str, dict] = {}
    for group in lineage.get("groups") or []:
        for entry in group.get("files") or []:
            name = (entry.get("as") or entry["file"]).split("/")[-1]
            record = describe(
                name, header=headers.get(name, {}), sha=shas.get(name),
                token=token, cache=cache,
            )
            if record:
                facts[name] = record
    if not facts:
        return ""
    body = yaml.dump(
        {"generated": generated, "files": facts},
        Dumper=_Dumper, sort_keys=False, width=100, default_flow_style=False,
    )
    return HEADER.format(generator=generator) + body
