apiVersion: v1
kind: Service
metadata:
  name: comfyui
  labels:
    app.kubernetes.io/name: comfyui
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: comfyui
  ports:
    - name: http
      port: 8188
      targetPort: http
